target-version = "py313"
fix = true
line-length = 100
src=["."]

[lint]
select = ["ALL"]
ignore = [
    "TD003",  # Disable TODO issue
    "D100",   # Missing docstring in public module
    "EXE002", # Use of `exec` statement
    "DTZ001", # Use of `datetime.now` instead of `datetime.utcnow`
    "D104",   # Missing docstring in public package
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line
    "ISC001", # Use of `is` with a literal
    "COM812", # Missing space after comment hash
]

fixable = ["ALL"]
