version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: matriculas-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matriculasdb
    ports:
      - "5432:5432"
    volumes:
      - matriculados_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  matriculados_data:
